apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/calungaproject/npm-registry?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main"
    # Independent promotes per merge; avoid snapshot supersession skipping releases.
    test.appstudio.openshift.io/ignore-supersession: "true"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: calunga-npm-registry-main
    appstudio.openshift.io/component: calunga-npm-registry-main
    pipelines.appstudio.openshift.io/type: build
  name: calunga-npm-registry-main-on-push
  namespace: calunga-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/calunga-tenant/calunga-npm-registry-main:{{revision}}
    - name: source-npm-image
      value: quay.io/redhat-user-workloads/calunga-tenant/calunga-npm-registry-main:on-pr-{{revision}}.npm
    - name: prev-packages-ref
      value: 'HEAD^'
    - name: git-clone-depth
      value: "0"
    - name: builder-image
      value: quay.io/redhat-user-workloads/calunga-tenant/npm-builder@sha256:9de06a22fd40563109fa6c758deb9d3b9f2bd56d173ad860c2d98c501da7d54a
    - name: task-promote-npm-oci-bundle
      value: quay.io/redhat-user-workloads/calunga-tenant/task-promote-npm-oci@sha256:edebf0d35e043cddc0975a9b6ae27fe9517a07b931064314fb669eb235f8bc6a
  taskRunTemplate:
    serviceAccountName: build-pipeline-calunga-npm-registry-main
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
  pipelineRef:
    name: promote-npm
  taskRunSpecs:
    - pipelineTaskName: promote-npm-oci
      computeResources:
        requests:
          memory: 2Gi
        limits:
          memory: 4Gi
status: {}
